FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
USER $APP_UID
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["src/SamoBot.Migrations/SamoBot.Migrations.csproj", "src/SamoBot.Migrations/"]
RUN dotnet restore "src/SamoBot.Migrations/SamoBot.Migrations.csproj"
COPY . .
WORKDIR "/src/src/SamoBot.Migrations"
RUN dotnet build "./SamoBot.Migrations.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
WORKDIR "/src/src/SamoBot.Migrations"
RUN dotnet publish "./SamoBot.Migrations.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "SamoBot.Migrations.dll"]
